### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by njlg** [launchdarkly/homebrew-tap#11] opened 2022-02-23 15:18 UTC
I get this message when I install the latest version:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the launchdarkly/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/launchdarkly/homebrew-tap/Formula/ld-find-code-refs.rb:9
```

**Comment by carmenquan** [comment] 2022-02-23 23:08
Thanks for reporting this @njlg, our team is looking into this and will update you as soon as we have an update.

**Comment by estraph** [comment] 2022-02-27 17:54
This is a dupe of https://github.com/launchdarkly/homebrew-tap/issues/9 - a fix was merged in https://github.com/launchdarkly/homebrew-tap/pull/10 but then a new update in https://github.com/launchdarkly/homebrew-tap/commit/76ab28f2864ca9cfede1d23b6acf27035c1106cf brought it back.

CC @InTheCloudDan

**Comment by InTheCloudDan** [comment] 2022-03-01 15:43
Hi @njlg and @estraph with our latest release `v.2.5.5` we've updated GoReleaser which includes the permanent fix for this. You should no longer receive the warning

**Closed by InTheCloudDan** 2022-03-01 15:43 UTC

**Comment by estraph** [comment] 2022-03-01 21:36
Lovely, thank you @InTheCloudDan
